<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite hostname="Amar" ignored="0" name="Default test" tests="1" failures="0" timestamp="21 Oct 2021 05:49:46 GMT" time="29.21" errors="0">
  <testcase name="readDATAfromCMD" time="29.119" classname="com.Vtiger.practice.AdminTest"/>
=======
<testsuite ignored="0" hostname="LAPTOP-DK6TK74Q" failures="1" tests="5" name="Default test" time="0.113" errors="0" timestamp="2021-10-21T16:19:33 IST">
  <testcase classname="com.Vtiger.SampleClassForRetryAnalyzer" name="sampleTest" time="0.015">
    <skipped/>
  </testcase> <!-- sampleTest -->
  <testcase classname="com.Vtiger.SampleClassForRetryAnalyzer" name="sampleTest" time="0.002">
    <skipped/>
  </testcase> <!-- sampleTest -->
  <testcase classname="com.Vtiger.SampleClassForRetryAnalyzer" name="sampleTest" time="0.002">
    <skipped/>
  </testcase> <!-- sampleTest -->
  <testcase classname="com.Vtiger.SampleClassForRetryAnalyzer" name="sampleTest" time="0.002">
    <skipped/>
  </testcase> <!-- sampleTest -->
  <testcase classname="com.Vtiger.SampleClassForRetryAnalyzer" name="sampleTest" time="0.001">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.Vtiger.SampleClassForRetryAnalyzer.sampleTest(SampleClassForRetryAnalyzer.java:10)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- sampleTest -->
>>>>>>> branch 'master' of https://github.com/pvpatil5/SDET_1_HYD.git
</testsuite> <!-- Default test -->
