<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="78694" started-at="2021-10-26T16:39:58 IST" finished-at="2021-10-26T16:41:17 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="78694" started-at="2021-10-26T16:39:58 IST" finished-at="2021-10-26T16:41:17 IST">
      <class name="com.Vtiger.TC_001_CreateOrgWith_DDTest">
        <test-method status="PASS" signature="startConnection()[pri:0, instance:com.Vtiger.TC_001_CreateOrgWith_DDTest@69b0fd6f]" name="startConnection" is-config="true" duration-ms="55" started-at="2021-10-26T16:39:58 IST" finished-at="2021-10-26T16:39:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startConnection -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:com.Vtiger.TC_001_CreateOrgWith_DDTest@69b0fd6f]" name="launchBrowser" is-config="true" duration-ms="9148" started-at="2021-10-26T16:39:59 IST" finished-at="2021-10-26T16:40:08 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.Vtiger.TC_001_CreateOrgWith_DDTest@69b0fd6f]" name="login" is-config="true" duration-ms="10707" started-at="2021-10-26T16:40:08 IST" finished-at="2021-10-26T16:40:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="TC001_createOrgwithDD()[pri:0, instance:com.Vtiger.TC_001_CreateOrgWith_DDTest@69b0fd6f]" name="TC001_createOrgwithDD" duration-ms="50413" started-at="2021-10-26T16:40:19 IST" finished-at="2021-10-26T16:41:09 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.Vtiger.TC_001_CreateOrgWith_DDTest.TC001_createOrgwithDD(TC_001_CreateOrgWith_DDTest.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_createOrgwithDD -->
        <test-method status="PASS" signature="logout()[pri:0, instance:com.Vtiger.TC_001_CreateOrgWith_DDTest@69b0fd6f]" name="logout" is-config="true" duration-ms="4883" started-at="2021-10-26T16:41:10 IST" finished-at="2021-10-26T16:41:15 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.Vtiger.TC_001_CreateOrgWith_DDTest@69b0fd6f]" name="closeBrowser" is-config="true" duration-ms="2375" started-at="2021-10-26T16:41:15 IST" finished-at="2021-10-26T16:41:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="closeConnection()[pri:0, instance:com.Vtiger.TC_001_CreateOrgWith_DDTest@69b0fd6f]" name="closeConnection" is-config="true" duration-ms="1" started-at="2021-10-26T16:41:19 IST" finished-at="2021-10-26T16:41:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeConnection -->
      </class> <!-- com.Vtiger.TC_001_CreateOrgWith_DDTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
